services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: nextjs.Dockerfile
    container_name: nextjs
    networks:
      - weather_network

  frontend:
    build:
      context: ./frontend
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    container_name: nginx-reverse-proxy
    networks:
      - weather_network

networks:
  weather_network:
