services:
  frontend:
    build:
      context: ./frontend
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    container_name: nginx-reverse-proxy
    networks:
      - weather_network
      

networks:
  weather_network:
